name: Deploy to Lambda

on: push

jobs:
  environment_setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup python version
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

  deploy_shell_script:
    runs-on: ubuntu-latest
    needs: [environment_setup]
    
    steps:
      - uses: actions/checkout@v3
      - name: Run the bulid script
        run: sh bulid.sh
      
      - name: Moving the zip file to s3 location
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy to zip to AWS s3
        run: |
          ls 
          aws s3 cp trigger_sns/find_lastest_file.zip s3://src-lambda-hari/src_code


  deploy_to_lambda:
    runs-on: ubuntu-latest
    needs: [environment_setup,deploy_shell_script]

    steps:
      - uses: actions/checkout@v3
      - name: Moving the zip to lambda
        run: |
          aws lambda update-function-code \
                --function-name find_lastest_file \
                --s3-bucket src-lambda-hari \
                --s3-key src_code/find_lastest_file.zip
    